import { query } from '../config/database.js';
import type { ActivityLogEntry, PaginationParams } from 'shared';

export class ActivityLogService {
  /**
   * Log a new activity entry. The id and createdAt are auto-generated by the database.
   */
  async log(entry: Omit<ActivityLogEntry, 'id' | 'createdAt'>): Promise<void> {
    await query(
      `INSERT INTO activity_log_entries (user_id, component, operation, severity, description, recommended_action)
       VALUES ($1, $2, $3, $4, $5, $6)`,
      [
        entry.userId,
        entry.component,
        entry.operation,
        entry.severity,
        entry.description,
        entry.recommendedAction ?? null,
      ],
    );
  }

  /**
   * Retrieve paginated activity log entries for a user, ordered by most recent first.
   */
  async getEntries(userId: string, pagination: PaginationParams): Promise<ActivityLogEntry[]> {
    const offset = (pagination.page - 1) * pagination.limit;

    const result = await query(
      `SELECT id, user_id, component, operation, severity, description, recommended_action, created_at
       FROM activity_log_entries
       WHERE user_id = $1
       ORDER BY created_at DESC
       LIMIT $2 OFFSET $3`,
      [userId, pagination.limit, offset],
    );

    return result.rows.map((row: Record<string, unknown>) => ({
      id: row.id as string,
      userId: row.user_id as string,
      component: row.component as string,
      operation: row.operation as string,
      severity: row.severity as ActivityLogEntry['severity'],
      description: row.description as string,
      recommendedAction: (row.recommended_action as string) ?? undefined,
      createdAt: new Date(row.created_at as string),
    }));
  }
}
